-- roles
INSERT INTO roles VALUES (DEFAULT, 'ROLE_USER');
INSERT INTO roles VALUES (DEFAULT, 'ROLE_ADMIN');

INSERT INTO dealstatus VALUES (DEFAULT,'INITIATED');
INSERT INTO dealstatus VALUES (DEFAULT, 'IN PROCESS');
INSERT INTO dealstatus VALUES (DEFAULT, 'COMPLETED');